/**
 * Check the mock fixtures against what the backend actually serves.
 *
 *   npx tsx scripts/verify-fixtures.ts
 *
 * Two different questions, both worth asking:
 *
 *   1. Internal consistency -- the flow identity holds at every hour of every
 *      building, on both curves, and nothing except battery goes negative.
 *      That is the repo's own `checkFixtures()`, run for real rather than
 *      trusted.
 *
 *   2. Agreement with the backend -- the optimizer output in the fixtures
 *      matches what the backend computes for the same building. The fixtures
 *      are the fallback for when the API is unreachable, so a demo that shows
 *      different numbers depending on whether the backend happens to be up is
 *      worse than one with no fallback at all.
 *
 * Expected values come from a JSON file generated by running the backend's own
 * solver, so this script itself needs neither Python nor a database:
 *
 *     python ../backend/scripts/dump_fixture_truth.py
 *     npx tsx scripts/verify-fixtures.ts
 *
 * Regenerate it whenever the optimizer changes, and run this after touching
 * anything under src/mocks/. Point BACKEND_TRUTH elsewhere if the file is not
 * at the repository root.
 *
 * The truth file is dumped in `fixtures` forecast mode. `backtest` maps the
 * curves onto a real metered day and no static fixture could track that; what
 * is pinned here is that the two sides agree about the optimizer and the
 * contract, not about which day is on the screen.
 */

import { readFileSync } from 'node:fs';

import { checkFixtures, FIXTURES } from '../src/mocks/buildings';

const TRUTH_PATH = process.env.BACKEND_TRUTH ?? '../backend_truth.json';

/** How far a fixture may sit from the backend before it counts as wrong. */
const TOLERANCE_KW = 0.05;
const TOLERANCE_USD = 0.02;
/** State of charge is published to 0.1 of a point, same as everything else. */
const TOLERANCE_PCT = 0.05;

interface BackendTruth {
  baseline_grid: number[];
  optimized_grid: number[];
  optimized_battery: number[];
  optimized_ev: number[];
  optimized_hvac: number[];
  optimized_soc: number[];
  optimized_peak_kw: number;
  peak_reduction_kw: number;
  savings_usd: number;
  actions: unknown[];
}

function seriesDiff(label: string, got: number[], want: number[], tol: number): string[] {
  if (got.length !== want.length) {
    return [`${label}: ${got.length} points, backend has ${want.length}`];
  }
  const bad: string[] = [];
  for (let h = 0; h < got.length; h += 1) {
    if (Math.abs(got[h] - want[h]) > tol) {
      bad.push(`${label}[${h}] = ${got[h]}, backend ${want[h]}`);
    }
  }
  return bad.length > 4 ? [...bad.slice(0, 4), `... and ${bad.length - 4} more`] : bad;
}

function scalarDiff(label: string, got: number, want: number, tol: number): string[] {
  return Math.abs(got - want) > tol ? [`${label} = ${got}, backend ${want}`] : [];
}

function main(): void {
  let failed = false;

  const { violations, maxResidual } = checkFixtures();
  console.log("--- internal consistency (the repo's own checkFixtures) ---");
  console.log(`flow identity violations : ${violations.length}`);
  console.log(`worst residual           : ${maxResidual.toFixed(6)} kW`);
  if (violations.length > 0) {
    failed = true;
    violations.slice(0, 10).forEach((v) => console.log('   ', v));
  }

  let truth: Record<string, BackendTruth>;
  try {
    truth = JSON.parse(readFileSync(TRUTH_PATH, 'utf8')) as Record<string, BackendTruth>;
  } catch {
    console.log(`\n(no backend truth at ${TRUTH_PATH}; skipping the comparison)`);
    process.exit(failed ? 1 : 0);
  }

  console.log('\n--- agreement with the backend ---');
  for (const fixture of FIXTURES) {
    const id = fixture.building.id;
    const want = truth[id];
    if (!want) {
      console.log(`${id.padEnd(19)} no backend entry, skipped`);
      continue;
    }

    const plan = fixture.buildPlan('verify');
    const battery = fixture.optimizedFlows.map((f) => f.battery_kw);
    const ev = fixture.optimizedFlows.map((f) => f.ev_kw);
    const hvac = fixture.optimizedFlows.map((f) => f.hvac_kw);
    const soc = fixture.optimizedFlows.map((f) => f.battery_soc_pct);

    const problems: string[] = [
      ...seriesDiff('baseline_grid', fixture.baselineGrid, want.baseline_grid, TOLERANCE_KW),
      ...seriesDiff('optimized_grid', fixture.optimizedGrid, want.optimized_grid, TOLERANCE_KW),
      ...seriesDiff('battery', battery, want.optimized_battery, TOLERANCE_KW),
      ...seriesDiff('ev', ev, want.optimized_ev, TOLERANCE_KW),
      ...seriesDiff('hvac', hvac, want.optimized_hvac, TOLERANCE_KW),
      // The engine prices a 95% round trip, so its state of charge cannot be
      // recovered by walking the dispatch: it has to be transcribed, which
      // means it can go stale on its own and has to be checked on its own.
      ...seriesDiff('soc', soc, want.optimized_soc, TOLERANCE_PCT),
      ...scalarDiff('optimized_peak_kw', fixture.optimizedPeakKw, want.optimized_peak_kw, TOLERANCE_KW),
      ...scalarDiff('peak_reduction_kw', fixture.peakReductionKw, want.peak_reduction_kw, TOLERANCE_KW),
      ...scalarDiff('savings_usd', fixture.savingsUsd, want.savings_usd, TOLERANCE_USD),
    ];

    if (plan.actions.length !== want.actions.length) {
      problems.push(`${plan.actions.length} actions, backend has ${want.actions.length}`);
    }

    if (problems.length === 0) {
      console.log(
        `${id.padEnd(19)} OK   ${fixture.baselinePeakKw.toFixed(1)} -> ` +
          `${fixture.optimizedPeakKw.toFixed(1)} kW, $${fixture.savingsUsd.toFixed(2)}, ` +
          `${plan.actions.length} actions`,
      );
    } else {
      failed = true;
      console.log(`${id.padEnd(19)} MISMATCH`);
      problems.forEach((p) => console.log('   ', p));
    }
  }

  console.log(failed ? '\nFAILED' : '\nAll fixtures consistent and in step with the backend.');
  process.exit(failed ? 1 : 0);
}

main();
